### PR TITLE
Using TCK Tested JDK builds of OpenJDK

### PR DESCRIPTION
**Pull request by carldea**
The AdoptOpenJDK has been discontinued since July 2021. When using Zulu you get all the latest updated (TCK Tested) builds for all versions of OpenJDK. 
Also added are fixed (major) release version(s) such as 11.0.3. This is often a good practice whenever a build/test triggers (push/pull events) this can determine if the latest JDK (11) had failed the build vs something in your code that caused it. For example, when building with JDK 11.0.3 (fixed version) the build passes (green) and JDK 11 fails (red) will mean that the latest JDK (11) was the cause and not your code.

## Proposed Changes

  - Added a fixed release of JDK 11.0.3
  - Switch from 'adopt' to 'zulu'

## Testing
N/A GitHub Action workflow.

## Issues Fixed

Fixes: using 'zulu' as a JDK build distribution. The 'adopt' builds are discontinued. 
Test: GH workflows

### CODE REVIEW

**Comment by dlam** [comment]
Switching to zulu sounds fine to me, but doing a matrix on multiple versions seems, excessive - if you want to revert a couple of the changes and just switch to zulu, I'm happy to pull this in!

Thanks for raising this.

**Comment by carldea** [comment]
> Switching to zulu sounds fine to me, but doing a matrix on multiple versions seems, excessive - if you want to revert a couple of the changes and just switch to zulu, I'm happy to pull this in!
> 
> Thanks for raising this.

Sure, I can remove the matrix. I did notice my mistake of adding the os, distribution to the matrix (not being used). I will just make it use one version (the latest) of `JDK 11` & use 'zulu'

**Comment by dlam** [comment]
Please add a `Test: GH workflows` clause to the body of your PR as a footer and rebase your change so we can get the workflow passing!

**Comment by carldea** [comment]
I created another PR #251 (another branch, and reverted code to make it simpler). 👍🏼
Let me know what you think.

**Comment by dlam** [comment]
Thanks!

**Comment by ohbus** [comment]
@dlam Why did this get closed and not merged?

**Comment by ohbus** [comment]
> @dlam Why did this get closed and not merged?

Sorry, I see it did get merge but not the GitHub way!

My bad.

**Comment by dlam** [comment]
We use AOSP as our source of truth - github is just to expose built errors / output externally. We mirror GH changes into AOSP and then merge there to ensure all our time-proven checks pass, then mirror 1-way back to Github.

**Comment by ohbus** [comment]
> We use AOSP as our source of truth - github is just to expose built errors / output externally. We mirror GH changes into AOSP and then merge there to ensure all our time-proven checks pass, then mirror 1-way back to Github.

Yes this is a common practice for many open source projects that has been initiated by Google.

Thanks for the beautiful explanation. My bad to worry you with this. Sorry for the hassles.

**Pull request closed without merging**
