### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by yoonseopshin**
## Proposed Changes

- Fix typo in `Modifier.kt`

## Testing
Test: N/A doc change

### CODE REVIEW

**Comment by yoonseopshin** [comment]
Now I signed CLA, rescan please

**Review by liutikas — APPROVED** [review]

**Comment by liutikas** [comment]
It still seems to think that you haven't signed the CLA. Can you take a another look?

**Comment by yoonseopshin** [comment]
image
image

It seems that I have signed CLA, is there anything I need to check more?

**Comment by dlam** [comment]
Had to re-run the CLA check, you should be good now!

**Pull request closed without merging**
