### PR TITLE
Better events

### PR DESCRIPTION
**Pull request by tikurahul**
Test: N/A

### CODE REVIEW

**Review by dlam — APPROVED** [review]
For external contributors retrying changes, I suppose we expect them to go through the actions UI then?

**Comment by tikurahul** [comment]
No, the only way to re-trigger is by adding a comment. 💬

**Comment by dlam** [comment]
Even on their fork? Don't they have access to workflow_dispatch from their actions tab? I guess it doesn't matter since it retriggers on push anyway?

**Comment by ZacSweers** [comment]
One thing you can do is add comment hotwords and make your action hide or delete the comment when it's done. Example:

https://github.com/ZacSweers/rebase/blob/41a109c7fe042cc94419a72900e67150d40dc91e/entrypoint.sh#L97-L111

**Pull request closed without merging**
