### PR TITLE
Update compose-component-api-guidelines.md

### PR DESCRIPTION
**Pull request by JunJaBoy**
## Proposed Changes

  - updated useless space in the code snippet of document

## Testing

Test: None

## Issues Fixed
Fixes: None

### CODE REVIEW

**Review by liutikas — APPROVED** [review]

**Comment by JunJaBoy** [comment]
hmm.. I really don't know why the lint shows an error

**Comment by liutikas** [comment]
It wants to see `Test: ` tag in the commit message. Can you add `Test: None`?

**Comment by JunJaBoy** [comment]
updated :) can you please re-run the actions?

**Comment by JunJaBoy** [comment]
this pr has been closed :(

**Comment by liutikas** [comment]
It landed through our internal system, see https://github.com/androidx/androidx/commit/98eed92e1f84058e9d65c73d7db2d862b0004cb6

**Pull request closed without merging**
