### PR TITLE
[FragmentStrictMode] Detect calls to Fragment#setUserVisibleHint

### PR DESCRIPTION
**Pull request by simonschiller**
## Proposed Changes

  - Detect calls to `Fragment#setUserVisibleHint`

## Testing

Test: See `FragmentStrictModeTest#detectSetUserVisibleHint`

## Issues Fixed

Fixes: 153738974

### CODE REVIEW

**Comment by dlam** [comment]
Navigation build is broken atm, so please ignore that :smiley:

**Review by jbw0033 — APPROVED** [review]

**Review by ianhanniballake — APPROVED** [review]

**Comment by jbw0033** [comment]
Hey, could you rebase this? We uploaded jetifier to ignore this entire directory https://android-review.googlesource.com/c/platform/frameworks/support/+/1622522

**Comment by simonschiller** [comment]
Rebased ✅

**Comment by ianhanniballake** [comment]
PS: I forgot to mention how much I really appreciate these PRs @simonschiller. Really excited to see the progression here 💯

**Comment by simonschiller** [comment]
Happy to help 😊

**Pull request closed without merging**
