### PR TITLE
Call AbstractProgressFragment's onViewCreated

### PR DESCRIPTION
**Pull request by b95505017**
Install observation has been moved to onViewCreated since 29c5aee2bf2685e3bc2a0e38ca0290408aa65b11.

## Proposed Changes

  -
  -
  -

## Testing

Test: Describe how you tested your changes. Note that this line (with `Test:`) is required, your PR will not build without it!

## Issues Fixed

Fixes: [Optional] The bug on [https://issuetracker.google.com](https://issuetracker.google.com) being fixed

### CODE REVIEW

**Comment by dlam** [comment]
I recently fixed a build failure - could you rebase your changes and see if that gets `build-biometric` check to pass?

**Comment by dlam** [comment]
In general bug fixes in AndroidX are usually accompanied by an associated test - please also add a test if you believe this is a bug in navigation and fill out the `Test: <blah>` stanza with the test class you added it to.

**Comment by dlam** [comment]
You will also want to base your changes on top of `androidx-main` as we are switching tonight / tomorrow

**Comment by ianhanniballake** [comment]
Thanks for the pull request, but this has already been fixed internally in [this CL](https://android-review.googlesource.com/c/platform/frameworks/support/+/1529306) as per [b/169636207](https://issuetracker.google.com/169636207).

**Pull request closed without merging**
