### PR TITLE
Add Paging to contributable projects via GH to README

### PR DESCRIPTION
**Pull request by dlam**
Test: N/A docs change only

### CODE REVIEW

**Review by tikurahul — APPROVED** [review]

**Comment by tikurahul** [comment]
You will have to rebase your changes.

**Comment by dlam** [comment]
yep, was waiting for the fix to get merged in! thanks for following up here too.

**Comment by jshvarts** [comment]
I suggest updating the`[Workmanager]` link anchor to `[WorkManager]` in the same line in this PR as that's the official name of the library referenced.

**Comment by dlam** [comment]
> I suggest updating the`[Workmanager]` link anchor to `[WorkManager]` in the same line in this PR as that's the official name of the library referenced.

It already points to the correct library group folder, `work`.

**Comment by jshvarts** [comment]
I meant updating the casing for the clickable link anchor `Workmanager` -> `WorkManager` (uppercase "M")

**Pull request closed without merging**
