### PR TITLE
Add `MapSubject#containsKey` to Kruth

### PR DESCRIPTION
**Pull request by veyndan**
Test: ./gradlew test connectedCheck
Bug: 270612487

### CODE REVIEW

**Comment by dlam** [comment]
Do you mind rebasing to get the latest fixes for workflows?

**Comment by veyndan** [comment]
@dlam Done!

**Comment by dlam** [comment]
Looks like you have an extra semicolon :D

**Comment by veyndan** [comment]
Oops! Clearly my [copy-paste game](https://github.com/google/truth/blob/623b3c457a19c0232e7e07fc07eb31e6f7b2f474/core/src/test/java/com/google/common/truth/MapSubjectTest.java#L865-L930) could use some work 😅

**Review by dlam — APPROVED** [review]

**Comment by dlam** [comment]
Yeah sorry - I know our GH workflows have been super flaky, so not the best signal :(

**Pull request closed without merging**
