### PR TITLE
Use atomicfu in paging-common

### PR DESCRIPTION
**Pull request by veyndan**
Test: ./gradlew test connectedCheck
Bug: 270612487

### CODE REVIEW

**Review by claraf3 — COMMENTED** [review]
The [atomicfu library](https://github.com/Kotlin/kotlinx-atomicfu) seems to be in Beta. @ianhanniballake Does this conflict with our general policy to use stable libraries?

**Comment by dlam** [comment]
We can't use atomicfu in androidx just yet. We've had discussions for this before with compose and datastore. We have a very light dependency on it in nativeMain but it's not stable enough for jvm since we want to bring that stable in a reasonable timeframe.

**Comment by veyndan** [comment]
Makes sense. I decided to use atomicfu here purely because I saw it was already in your `libs.versions.toml` file, so I assumed that you're good with using it.

Multiplatform Paging currently doesn't depend on atomicfu, but instead depends on [Stately Concurrency](https://github.com/touchlab/Stately). If you look at the source code, on the JVM, it just [directly typealiases to `java.util.concurrent.atomic.*`](https://github.com/touchlab/Stately/blob/main/stately-concurrency/src/jvmMain/kotlin/co/touchlab/stately/concurrency/AtomicInt.kt).

Would you be okay with switching over to Stately Concurrency for this PR instead (which _is_ stable)?

**Comment by veyndan** [comment]
FYI I've already proposed the usage of Stately in https://github.com/androidx/androidx/pull/518

**Comment by claraf3** [comment]
Thanks again for your patience on this PR. Im a bit swamped right now but I'll get to this PR as soon as I can. I need to explore other options / write our own locks(?) as we also want to avoid using Stately for this as well.

**Comment by claraf3** [comment]
Hi @veyndan just wanted to update you -- we want to hold off on adding new dependencies until we cut Paging 3.2, so this PR will be part of Paging 3.3. This should happen within the month.

**Comment by claraf3** [comment]
Ended up using stately for Atomics in #577, closing this one as duplicate.

**Pull request closed without merging**
