### PR TITLE
[Navigation] Fix tests in NavDeepLinkTest

### PR DESCRIPTION
**Pull request by osipxd**
There were tests that actually did not what was declared in assert.

## Testing

Test: ./gradlew connectedCheck

### CODE REVIEW

**Comment by sanura-njaka** [comment]
Hi Osip, looks like you are failing a Presubmit check. Looks like you may just need to update and re-sync your gradle.

**Comment by osipxd** [comment]
@sanura-njaka, yes, I see. But I don't understand how changes in tests in module `navigation-common` affect task `compileReleaseKotlin` in module `navigation-compose` 🤔 
How can I fix it? I've already pulled the latest commits from upstream, but the problem is still here.

```
> Task :navigation:navigation-compose:compileReleaseKotlin FAILED
e: This version (1.1.0-alpha01) of the Compose Compiler requires Kotlin version 1.5.10 but you appear to be using Kotlin version 1.5.21 which is not known to be compatible.  Please fix your configuration (or `suppressKotlinVersionCompatibilityCheck` but don't say I didn't warn you!).
```

**Comment by dlam** [comment]
I'll take a look, might be an issue on our end!

**Comment by dlam** [comment]
Turns out this was an issue on our end - it should be fixed now, can you rebase and try again? Sorry about the back and forth.

**Comment by osipxd** [comment]
@dlam, Done

**Review by sanura-njaka — APPROVED** [review]
Looks good! Thanks for separating this out!

**Review by dlam — APPROVED** [review]

**Pull request closed without merging**
