### PR TITLE
Fix issue caused by custom classloader.

### PR DESCRIPTION
**Pull request by Notzuonotdied**
## Proposed Changes

 - Passing the specified class loader to fix ClassNotFoundException when app contains multiple class loaders.

## Testing

Test: ./gradlew test connectedCheck -x :room:room-benchmark:cC -x :room:integration-tests:room-incremental-annotation-processing:test;./gradlew updateApi

## Issues Fixed

Fixes: The bug on [170141113](https://issuetracker.google.com/issues/170141113) being fixed

### CODE REVIEW

**Comment by dlam** [comment]
@tikurahul Is the PR description check failing incorrectly here?

**Review by yigit — APPROVED** [review]
thanks!

**Review by danysantiago — APPROVED** [review]

**Comment by dlam** [comment]
This change needs to be rebased on top of androidx-master-dev to pull in fixes for the build related to paging-samples

**Comment by Notzuonotdied** [comment]
> This change needs to be rebased on top of androidx-master-dev to pull in fixes for the build related to paging-samples

Should I merge the commits into my repository from `androidx:androidx-master-dev` and resubmit it?

**Comment by dlam** [comment]
No need, things are green now! Only the state of the branch you made the PR from matters, and it seems you fixed that. Thank you!

**Pull request closed without merging**
