### PR TITLE
Fix dangling javadoc

### PR DESCRIPTION
**Pull request by zactestaccount**
Hi it's Zac from a test account!

Test: It compiles without martians invading

### CODE REVIEW

**Comment by zactestaccount** [comment]
CC @dlam

**Comment by tikurahul** [comment]
@zactestaccount You will need a `Test`  stanza in the pull request body. 

Something like `Test: N/A`.

**Comment by zactestaccount** [comment]
Updated the body, is that enough to re-kick?

**Review by dlam — APPROVED** [review]

**Comment by tikurahul** [comment]
https://github.com/androidx/androidx/pull/43/checks?check_run_id=905231998 😄

**Comment by zactestaccount** [comment]
image

**Comment by tikurahul** [comment]
@zactestaccount your build was successful ! 🛩️

**Pull request closed without merging**
